#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Wed Sep 16 08:06:23 MSK 2026
another_furniture=true
create=true
farmersdelight=true
mcwfurnitures=true
storagedrawers=true
twilightforest=true
